<?php

/**
 * @file
 * Drupal Module: Chalk Display.
 *
 * Implements theme hook.
 *
 * @author: Christophe Jossart <https://www.drupal.org/user/2295486>
 */

/**
 * Implements hook_theme.
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function chalk_display_theme($existing, $type, $theme, $path) {
  return array(
    'chalk_display_social_links' => array(
      'variables' => array(
        'title' => null,
        'social_links' => null,
      ),
      'template' => 'social_links',
    ),
    'chalk_display_more_boards' => array(
      'variables' => array(
        'title' => null,
        'previous' => null,
        'next' => null,
      ),
      'template' => 'more_boards',
    ),
    'chalk_display_more_artists' => array(
      'variables' => array(
        'title' => null,
        'previous' => null,
        'next' => null,
      ),
      'template' => 'more_artists',
    ),
    'chalk_display_hero' => array(
      'variables' => array(
        'video' => null,
        'aquarelle' => null,
      ),
      'template' => 'hero',
    ),
  );
}
