<?php

/**
 * @file
 * Drupal Module: Chalk Display.
 *
 * @author: Christophe Jossart <https://www.drupal.org/user/2295486>
 */

/**
 * Implements hook_theme().
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function chalk_display_theme($existing, $type, $theme, $path)
{
  return array(
    'chalk_display_meet' => array(
      'variables' => array(
        'meet_link' => null,
      ),
      'template' => 'meet',
    ),
    'chalk_display_footer' => array(
      'variables' => array(
        'contact' => null,
        'social_links' => null,
        'credits' => null,
      ),
      'template' => 'footer',
    ),
  );
}